INSERT INTO cat (name, photo_path, rate) values
    ('Саня', '/images/1.jpg', 0),
    ('Буся','/images/2.jpg', 0),
    ('Олег','/images/3.jpg', 0),
    ('Липатий','/images/4.jpg', 0),
    ('Мурка','/images/5.jpg', 0),
    ('Дуся','/images/6.jpg', 0),
    ('Киса', '/images/7.jpg', 0),
    ('Бублик', '/images/8.jpg', 0),
    ('Рыжик', '/images/9.jpg', 0),
    ('Арахис', '/images/10.jpg', 0),
    ('Ариэль', '/images/11.jpg', 0),
    ('Бандит', '/images/12.jpg', 0),
    ('Бенедикт', '/images/13.jpg', 0),
    ('Лулу', '/images/14.jpg', 0),
    ('Мия','/images/15.jpg', 0),
    ('Платон','/images/16.jpg', 0),
    ('Ирис','/images/17.jpg', 0),
    ('Дейзи','/images/18.jpg', 0),
    ('Коля','/images/19.jpg', 0),
    ('Мисик','/images/20.jpg', 0),
    ('Роман','/images/21.jpg', 0),
    ('Чижик','/images/22.jpg', 0),
    ('Мурзик','/images/23.jpg', 0);